language: node_js
node_js:
- node
- '6'
install:
- npm run setup
deploy:
- provider: lambda
  function_name: parliament
  region: eu-west-1
  role: arn:aws:iam::665717792942:role/service-role/parliament
  runtime: nodejs6.10
  handler_name: handler
  access_key_id: AKIAIFFNHGLEZAPXF4NA
  secret_access_key:
    secure: XlcopeoTYVojhyu7NGt9AZDrlYgvceJ3II21NZx5W5ESbSpclnxYSajmLCELufbvAWuTM++ccGlSWhj3rgBBd8jc7Aj0aGhVhuptBFenKsHzJFrheR577rpN+v4krAv+LAobPCzVhTiOaCTq1eX36yG4drXrgNMaOUDClybv7iVPKfTLCET2B00cpwPfvVV0D7y2VxxKUtsp96FmT/T3DC4X2MAagFIKsy52EZPuH2Fq7eVCSIMyneSez8ymTjq2TvN+YzS8xH/CCb0DqX3rX2NLwxAcnyWousUA0CPxUECUnViuC6/YUqtumWmeC1w1bKWOdUNZZwCP+f/PwYZfqRtHc6Hiri2BU/eChN/71geTRRyyWTkkxZnBHlv5UcK9xIBNNpOxGvF9YBM3H2lH+9BhmLRmBGKzrCI46ibFtI2gYTyRxTrsKjT8858rbNgtY1queRV0y2FtrHRF8R/KJurs93P20G5BJbvEdiulVREO/3rdAL8fCAhwYRolOZULWrkZBMNlQao7UHVWfoodcxItR2KtY78m5Lr7LdSpvUXosVluOzfx5nxBwW5V6mlBaH4nIm+6zCWV8W1YZXSkJRyDAZShKF6vmwxLa3jVqOzNg4l6PM4ZTkpil0RNsOL1S+bg94nBf9GNaI1Z2mIT5XlBegyk1NKHBflVOpqifMU=
  on:
    tags: true
- provider: lambda
  function_name: parliamentTest
  region: eu-west-1
  role: arn:aws:iam::665717792942:role/service-role/parliament
  runtime: nodejs6.10
  handler_name: handler
  access_key_id: AKIAIFFNHGLEZAPXF4NA
  secret_access_key:
    secure: XlcopeoTYVojhyu7NGt9AZDrlYgvceJ3II21NZx5W5ESbSpclnxYSajmLCELufbvAWuTM++ccGlSWhj3rgBBd8jc7Aj0aGhVhuptBFenKsHzJFrheR577rpN+v4krAv+LAobPCzVhTiOaCTq1eX36yG4drXrgNMaOUDClybv7iVPKfTLCET2B00cpwPfvVV0D7y2VxxKUtsp96FmT/T3DC4X2MAagFIKsy52EZPuH2Fq7eVCSIMyneSez8ymTjq2TvN+YzS8xH/CCb0DqX3rX2NLwxAcnyWousUA0CPxUECUnViuC6/YUqtumWmeC1w1bKWOdUNZZwCP+f/PwYZfqRtHc6Hiri2BU/eChN/71geTRRyyWTkkxZnBHlv5UcK9xIBNNpOxGvF9YBM3H2lH+9BhmLRmBGKzrCI46ibFtI2gYTyRxTrsKjT8858rbNgtY1queRV0y2FtrHRF8R/KJurs93P20G5BJbvEdiulVREO/3rdAL8fCAhwYRolOZULWrkZBMNlQao7UHVWfoodcxItR2KtY78m5Lr7LdSpvUXosVluOzfx5nxBwW5V6mlBaH4nIm+6zCWV8W1YZXSkJRyDAZShKF6vmwxLa3jVqOzNg4l6PM4ZTkpil0RNsOL1S+bg94nBf9GNaI1Z2mIT5XlBegyk1NKHBflVOpqifMU=
  on:
    branch: "master"

